import { constants } from "node:fs";
import { access, readFile, readdir, rm } from "node:fs/promises";
import { join, resolve } from "node:path";
import { cleanFilterScriptName } from "#/app/commands/init/constants";
import { bshopifyStateDir } from "#/app/runner/constants";
import { refreshGitIndexForRestoredFiles } from "#/app/runner/git-refresh";
import { restoreFileTransactionJournal } from "#/app/runner/transaction";
import { isNodeError } from "#/utils/node";
import { formatPath } from "#/utils/paths";
import { isGitRepository, resolveGitTopLevel } from "./git";
import type { ClearResult } from "./types";

const lockFileName = "extension-prepare.lock";
const transactionFileName = "extension-prepare.transaction.json";

/**
 * Returns the pid holding the bshopify prepare lock when that process is
 * still alive, which means an `app dev` / `app deploy` session is running.
 */
export async function findLivePreparePid(cwd: string): Promise<number | undefined> {
  return readRunningLockPid(join(cwd, bshopifyStateDir, lockFileName));
}

/**
 * Restores any pending extension injection recorded in the bshopify
 * transaction journal before the state directory is removed, so source files
 * are left with their placeholders rather than temporary injected values.
 * Callers must ensure no live dev/deploy process holds the prepare lock.
 */
export async function restorePendingTransaction(
  cwd: string,
  result: ClearResult,
): Promise<void> {
  const journalPath = join(cwd, bshopifyStateDir, transactionFileName);

  if (!(await pathExists(journalPath))) {
    return;
  }

  try {
    const restoredFiles = await restoreFileTransactionJournal(journalPath);
    await refreshGitIndexForRestoredFiles(cwd, restoredFiles);

    result.updated.push(
      restoredFiles.length > 0
        ? "restored pending bshopify injections"
        : "cleaned stale bshopify transaction journal",
    );
  } catch (error) {
    result.warnings.push(
      `failed to restore pending bshopify injections: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
}

/** Deletes the project state directory (manifest, locks, journals, scripts). */
export async function removeStateDir(cwd: string, result: ClearResult): Promise<void> {
  const stateDir = join(cwd, bshopifyStateDir);

  if (!(await pathExists(stateDir))) {
    return;
  }

  await rm(stateDir, { force: true, recursive: true });
  result.removed.push(`${bshopifyStateDir}/`);
}

/**
 * In a monorepo the git clean filter script is written to the repository top
 * level's state directory instead of the project one, so it is removed
 * separately after the project state directory has been deleted.
 */
export async function removeTopLevelCleanerScript(
  cwd: string,
  result: ClearResult,
): Promise<void> {
  if (!(await isGitRepository(cwd))) {
    return;
  }

  const topLevel = await resolveGitTopLevel(cwd);
  if (topLevel === undefined || resolve(topLevel) === resolve(cwd)) {
    return;
  }

  const scriptPath = join(topLevel, cleanFilterScriptName);
  if (!(await pathExists(scriptPath))) {
    return;
  }

  const script = await readFile(scriptPath, "utf8");
  if (!script.includes("Generated by bshopify")) {
    result.warnings.push(`kept non-bshopify file ${formatPath(cwd, scriptPath)}`);
    return;
  }

  await rm(scriptPath, { force: true });
  result.removed.push(formatPath(cwd, scriptPath));
  await removeStateDirIfEmpty(join(topLevel, bshopifyStateDir), result, cwd);
}

async function readRunningLockPid(lockPath: string): Promise<number | undefined> {
  if (!(await pathExists(lockPath))) {
    return undefined;
  }

  let content = "";
  try {
    content = await readFile(lockPath, "utf8");
  } catch (error) {
    if (isNodeError(error) && error.code === "ENOENT") {
      return undefined;
    }

    throw error;
  }

  const pid = Number(content.trim());
  if (!Number.isInteger(pid) || pid <= 0) {
    return undefined;
  }

  return isProcessRunning(pid) ? pid : undefined;
}

function isProcessRunning(pid: number): boolean {
  try {
    process.kill(pid, 0);
    return true;
  } catch (error) {
    if (isNodeError(error) && error.code === "ESRCH") {
      return false;
    }

    return true;
  }
}

async function removeStateDirIfEmpty(
  dir: string,
  result: ClearResult,
  cwd: string,
): Promise<void> {
  let entries: string[] = [];

  try {
    entries = await readdir(dir);
  } catch (error) {
    if (isNodeError(error) && error.code === "ENOENT") {
      return;
    }

    throw error;
  }

  if (entries.length > 0) {
    return;
  }

  await rm(dir, { force: true });
  result.removed.push(formatPath(cwd, dir));
}

async function pathExists(path: string): Promise<boolean> {
  try {
    await access(path, constants.F_OK);
    return true;
  } catch (error) {
    if (isNodeError(error) && error.code === "ENOENT") {
      return false;
    }

    throw error;
  }
}
