import { basename, isAbsolute, join, normalize, sep } from "node:path";
import { loadOptionalDefaultExport } from "#/utils/config";
import { isRecord, toNonEmptyString, toStringRecord } from "#/utils/objects";
import { ansi, colorize } from "#/utils/output";
import type { EnvFilesConfig, RunnerConfig, RunnerConfigInput } from "./types";

/**
 * Vite-style type helper for `bshopify.config.mjs`. It is an identity
 * function: it only exists so the config's default export gets full type
 * checking and editor hints, mirroring `defineConfig` in Vite / tsup:
 *
 * ```js
 * // @ts-check
 * import { defineConfig } from "@standhigher/bshopify";
 *
 * export default defineConfig({
 *   configFiles: { dev: "shopify.app.dev.toml" },
 * });
 * ```
 *
 * The CLI loads the config with a plain dynamic `import()` of the file, so
 * this form requires the package to be installed (and importable) in the
 * project that owns the config. When the CLI is used globally and the
 * project does not install the package, the config template generated by
 * `init` instead inlines a self-contained JSDoc typedef (with a leading
 * `// @ts-check`), so editors validate the default export with no package
 * import at all.
 */
export function defineConfig(config: RunnerConfigInput): RunnerConfigInput {
  return config;
}

export const defaultRunnerConfig: RunnerConfig = {
  configFiles: {
    dev: "shopify.app.dev.toml",
    test: "shopify.app.test.toml",
    production: "shopify.app.production.toml",
  },
  envFiles: {},
  // Internal defaults: not exposed in generated configs, but still loadable
  // from existing configs for backward compatibility.
  entryFileName: "__entry.js",
  extensionsRoot: "extensions",
  failOnUnresolvedPlaceholders: true,
  restoreMarkers: true,
};

export async function loadRunnerConfig(cwd: string): Promise<RunnerConfig> {
  const configPath = join(cwd, "bshopify.config.mjs");
  const configModule = await loadOptionalDefaultExport(configPath);
  const loaded = isRecord(configModule) ? configModule : {};
  const configFiles = isRecord(loaded.configFiles)
    ? validateConfigFiles(toStringRecord(loaded.configFiles))
    : defaultRunnerConfig.configFiles;
  const envFiles = parseEnvFiles(loaded.envFiles);

  return {
    configFiles,
    envFiles,
    entryFileName: toNonEmptyString(loaded.entryFileName, defaultRunnerConfig.entryFileName),
    extensionsRoot: toNonEmptyString(loaded.extensionsRoot, defaultRunnerConfig.extensionsRoot),
    failOnUnresolvedPlaceholders:
      typeof loaded.failOnUnresolvedPlaceholders === "boolean"
        ? loaded.failOnUnresolvedPlaceholders
        : defaultRunnerConfig.failOnUnresolvedPlaceholders,
    restoreMarkers:
      typeof loaded.restoreMarkers === "boolean"
        ? loaded.restoreMarkers
        : defaultRunnerConfig.restoreMarkers,
  };
}

export function getShopifyCliConfigName(configFile: string): string {
  const fileName = basename(configFile);
  const withoutToml = fileName.endsWith(".toml") ? fileName.slice(0, -".toml".length) : fileName;

  if (withoutToml === "shopify.app") {
    return fileName;
  }

  return withoutToml.startsWith("shopify.app.")
    ? withoutToml.slice("shopify.app.".length)
    : withoutToml;
}

export function formatShopifyCliConfigArgs(configName: string | undefined): string[] {
  return configName === undefined || configName.length === 0 ? [] : ["--config", configName];
}

export function withoutShopifyCliConfigArgs(args: string[]): string[] {
  const result: string[] = [];

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];

    if (arg === undefined) {
      continue;
    }

    if (arg === "--config" || arg === "-c") {
      const next = args[index + 1];

      if (next !== undefined && !next.startsWith("-")) {
        index += 1;
      }

      continue;
    }

    if (arg.startsWith("--config=") || arg.startsWith("-c=")) {
      continue;
    }

    result.push(arg);
  }

  return result;
}

export function formatShopifyCliForwardedArgs(
  configFile: string,
  shopifyArgs: string[] = [],
): string[] {
  const forwardedArgs = withoutShopifyCliConfigArgs(shopifyArgs);

  if (forwardedArgs.length !== shopifyArgs.length) {
    console.warn(
      colorize(
        "Ignored --config / -c in extra Shopify args. Use bshopify --config <key> to select a configFiles environment.",
        ansi.yellow,
      ),
    );
  }

  return [
    ...formatShopifyCliConfigArgs(getShopifyCliConfigName(configFile)),
    ...forwardedArgs,
  ];
}

function validateConfigFiles(configFiles: Record<string, string>): Record<string, string> {
  for (const [configName, configFile] of Object.entries(configFiles)) {
    if (configFile.trim().length === 0) {
      continue;
    }

    if (!isRootShopifyAppConfigFile(configFile)) {
      throw new Error(
        `bshopify configFiles.${configName} must be a root-level Shopify app config file: shopify.app.toml or shopify.app.<name>.toml.`,
      );
    }
  }

  return configFiles;
}

function isRootShopifyAppConfigFile(configFile: string): boolean {
  return (
    basename(configFile) === configFile
    && /^shopify\.app(?:\.[^/\\]+)?\.toml$/.test(configFile)
  );
}

const RESERVED_ENV_FILE_KEYS = new Set(["configPath", "env", "appConfig"]);
const ENV_FILE_KEY_PATTERN = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function parseEnvFiles(value: unknown): EnvFilesConfig {
  if (value === undefined) {
    return {};
  }

  if (isRecord(value)) {
    return validateEnvFiles(value);
  }

  console.warn(
    colorize("bshopify envFiles must be an object; treated as empty.", ansi.yellow),
  );
  return {};
}

function validateEnvFiles(value: Record<string, unknown>): EnvFilesConfig {
  const result: EnvFilesConfig = {};

  for (const [key, entry] of Object.entries(value)) {
    validateEnvFileKey(key);

    if (typeof entry === "string") {
      result[key] = validateEnvFilePath(key, entry);
      continue;
    }

    if (
      Array.isArray(entry)
      && entry.length > 0
      && entry.every((item) => typeof item === "string")
    ) {
      result[key] = (entry as string[]).map((path) => validateEnvFilePath(key, path));
      continue;
    }

    throw new Error(
      `bshopify envFiles.${key} must be a file path or a non-empty array of file paths.`,
    );
  }

  return result;
}

function validateEnvFileKey(key: string): void {
  if (!ENV_FILE_KEY_PATTERN.test(key)) {
    throw new Error(`bshopify envFiles key "${key}" must be a valid JavaScript identifier.`);
  }

  if (RESERVED_ENV_FILE_KEYS.has(key) || key in Object.prototype) {
    throw new Error(`bshopify envFiles key "${key}" is reserved.`);
  }
}

function validateEnvFilePath(key: string, path: string): string {
  const trimmed = path.trim();

  if (trimmed.length === 0) {
    throw new Error(`bshopify envFiles.${key} path must not be empty.`);
  }

  if (isAbsolute(trimmed)) {
    throw new Error(
      `bshopify envFiles.${key} path must be relative to the project root: ${trimmed}`,
    );
  }

  const normalized = normalize(trimmed);

  if (normalized === ".." || normalized.startsWith(`..${sep}`)) {
    throw new Error(
      `bshopify envFiles.${key} path must stay inside the project root: ${trimmed}`,
    );
  }

  return trimmed;
}
