export { createCliProgram, runCli, runShopifyCommand } from "./main";
export { packageInfo } from "./utils/package-json";
export { clearProject, formatClearResult } from "./app/commands/clear";
export { deployProject } from "./app/commands/deploy";
export { devProject } from "./app/commands/dev";
export { formatInitResult, initProject } from "./app/commands/init";
export { defineConfig } from "./app/runner/config";
export { getAutoUpgradeEnabled, setAutoUpgradeEnabled } from "./upgrade/auto-upgrade-state";
export { createConfigCommand, createUpgradeCommand, runUpgrade } from "./upgrade/commands";
export {
  maybeAutoUpgrade,
  spawnDetachedAutoUpgradeWorker,
  triggerAutoUpgrade,
} from "./upgrade/trigger";

export type { CliDependencies, ProcessRunner, ShopifyCommandRunner } from "./main";
export type {
  ConfigAutoupgradeDependencies,
  UpgradeDependencies,
} from "./upgrade/commands";
export type { AutoUpgradeTriggerDependencies } from "./upgrade/trigger";
export type { PackageInfo } from "./utils/package-json";
export type { ClearOptions, ClearResult } from "./app/commands/clear/types";
export type { DeployOptions } from "./app/runner/types";
export type { DevOptions } from "./app/runner/types";
export type { InitCheck, InitOptions, InitResult } from "./app/commands/init/types";

// bshopify.config.mjs typing: the config template generated by `init`
// inlines a self-contained JSDoc typedef of the team-facing config surface
// (no package import), so global-only installs get editor hints too;
// `defineConfig` offers the same hints with a Vite-style helper when the
// config imports the package.
export type { RunnerConfigInput } from "./app/runner/types";

// Extension entry lifecycle types: what `__entry.js` authors need to type
// their prepare / validate / beforeDeploy / afterDeploy / onError hooks.
// The generated entry template inlines self-contained JSDoc typedefs instead
// (no package import), so global-only installs get editor hints too.
export type {
  ExtensionContext,
  ExtensionDeployResult,
  ExtensionInfo,
  ExtensionLifecycle,
  ExtensionPlanResult,
  InjectionPlan,
  ManagedEntry,
  PreparedExtensionPlan,
} from "./extension/types";
